# Generated by Django 5.2.7 on 2025-11-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_activitylog_api_activitylog_user_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
